name: NuGet Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create build directory
      run: mkdir build
      working-directory: lib/CRoaring

    - name: Run cmake generate
      run: cmake -DBUILD_SHARED_LIBS=ON -DNO_SONAME=ON ..
      working-directory: lib/CRoaring/build

    - name: Run cmake
      run: cmake --build . --target roaring
      working-directory: lib/CRoaring/build

    - name: Copy build directory
      run: ls
      working-directory: lib/CRoaring/build


    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build
    #   run: dotnet build --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
